spring:
  application:
    name: service-gateway

server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: service-auth
    mqtt:
      path: /mqtt/**
      sensitiveHeaders:
      serviceId: service-mqtt
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8082/uaa/oauth/token
      user-authorization-uri: http://localhost:8082/uaa/oauth/authorize
      client-id: client
    resource:
      user-info-uri: http://localhost:8082/uaa/current
      prefer-token-info: false