spring:
  application:
    name: service-mqtt

server:
  port: 8070

msg: Hello

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


security:
  oauth2:
    resource:
      id: service-mqtt
      user-info-uri: http://localhost:8082/uaa/current
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG

ywh:
  mqtt:
    broker: 39.104.49.84
    port: 1883
    qos: 1

mqttRootTopic: aiwu