server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: service-auth
  profiles:
    active: pro

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://118.190.202.155:3306/ywh_iot_test
    username: root
    password: Ywh@68531026
    driver-class-name: com.mysql.jdbc.Driver

logging.level.org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3