spring:
  application:
    name: service-mqtt
  profiles:
    active: dev
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  datasource:
      url: jdbc:mysql://localhost:3306/ywh_iot_test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8070

msg: Hello

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


security:
  oauth2:
    resource:
      id: service-mqtt
      user-info-uri: http://localhost:8082/uaa/current
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG

ywh:
  mqtt:
    broker: 39.104.49.84
    port: 1883
    qos: 1

mqttRootTopic: /device